<?php

declare(strict_types=1);

namespace PraiseDare\Monnify\Data\Payments\Responses;

use PraiseDare\Monnify\Data\MonnifyResponse;

/**
 * Response DTO for payment initialization
 */
class InitiatePaymentResponse extends MonnifyResponse
{
    public function __construct(
        bool $requestSuccessful,
        string $responseMessage,
        string $responseCode,
        ?InitiatePaymentResponseBody $responseBody,
    ) {
        parent::__construct($requestSuccessful, $responseMessage, $responseCode, $responseBody);
    }

    /**
     * Create from array
     */
    public static function fromArray(array $data): self
    {
        return new self(
            requestSuccessful: $data['requestSuccessful'],
            responseMessage: $data['responseMessage'],
            responseCode: $data['responseCode'],
            responseBody: isset($data['responseBody']) && is_array($data['responseBody'])
                ? InitiatePaymentResponseBody::fromArray($data['responseBody'])
                : null,
        );
    }

    /**
     * Convert to array
     */
    public function toArray(): array
    {
        return [
            'requestSuccessful' => $this->requestSuccessful,
            'responseMessage' => $this->responseMessage,
            'responseCode' => $this->responseCode,
            'responseBody' => $this->responseBody?->toArray(),
        ];
    }

    /**
     * Get payment URL
     */
    public function getPaymentUrl(): string
    {
        return $this->responseBody->checkoutUrl;
    }

    /**
     * Get the Monnify-generated transaction reference
     */
    public function getTransactionReference(): string
    {
        return $this->responseBody->transactionReference;
    }

    /**
     * Get the user-supplied payment reference
     */
    public function getPaymentReference(): string
    {
        return $this->responseBody->paymentReference;
    }
}

/**
 * Response body DTO for payment initialization
 */
class InitiatePaymentResponseBody
{
    public function __construct(
        /**
         * The reference generated by Monnify to identify this transaction
         */
        public readonly string $transactionReference,
        /**
         * The user-supplied payment reference
         */
        public readonly string $paymentReference,
        public readonly string $merchantName,
        public readonly string $apiKey,
        public readonly array $enabledPaymentMethod,
        public readonly string $checkoutUrl,
    ) {
    }

    /**
     * Create from array
     */
    public static function fromArray(array $data): self
    {
        return new self(
            transactionReference: $data['transactionReference'],
            paymentReference: $data['paymentReference'],
            merchantName: $data['merchantName'],
            apiKey: $data['apiKey'],
            enabledPaymentMethod: $data['enabledPaymentMethod'],
            checkoutUrl: $data['checkoutUrl'],
        );
    }

    /**
     * Convert to array
     */
    public function toArray(): array
    {
        return [
            'transactionReference' => $this->transactionReference,
            'paymentReference' => $this->paymentReference,
            'merchantName' => $this->merchantName,
            'apiKey' => $this->apiKey,
            'enabledPaymentMethod' => $this->enabledPaymentMethod,
            'checkoutUrl' => $this->checkoutUrl,
        ];
    }
}