<?php

namespace PraiseDare\Monnify\Enums;

enum WebhookEvents: string
{
    case SUCCESSFUL_TRANSACTION = 'SUCCESSFUL_TRANSACTION';
    case FAILED_TRANSACTION = 'FAILED_TRANSACTION';
    case PENDING_TRANSACTION = 'PENDING_TRANSACTION';
    case SUCCESSFUL_REFUND = 'SUCCESSFUL_REFUND';
    case FAILED_REFUND = 'FAILED_REFUND';
    case SETTLEMENT_COMPLETION = 'SETTLEMENT_COMPLETION';
    case SUCCESSFUL_DISBURSEMENT = 'SUCCESSFUL_DISBURSEMENT';
    case FAILED_DISBURSEMENT = 'FAILED_DISBURSEMENT';
    case REVERSED_DISBURSEMENT = 'REVERSED_DISBURSEMENT';
}
